# backend/app/routers/shopping_list.py
from fastapi import APIRouter, Depends, Request, HTTPException, status
from sqlalchemy.orm import Session
from typing import Annotated, List

from .. import crud, models, schemas, security
from ..database import get_db
from ..limiter import limiter

router = APIRouter(
    prefix="/shopping-list",
    tags=["Shopping List"],
    dependencies=[Depends(security.get_current_active_user)]
)

DbDependency = Annotated[Session, Depends(get_db)]
ManagerOrAdminDependency = Annotated[models.User, Depends(security.require_role(["admin", "project manager"]))]
CurrentUserDependency = Annotated[models.User, Depends(security.get_current_active_user)]


@router.get("/project/{project_id}", response_model=List[schemas.ShoppingListItem])
@limiter.limit("100/minute")
async def read_project_shopping_list(
    request: Request,
    project_id: int,
    db: DbDependency,
    current_user: CurrentUserDependency
):
    """
    Retrieves the calculated shopping list for a specific project.
    
    The shopping list is generated by comparing the Bill of Quantities (BoQ) 
    requirements against the current on-site project inventory.
    """
    
    # 1. Permission Check: Determine tenant scope
    # Superadmins (God Mode) have effective_tenant_id = None to bypass filters
    effective_tenant_id = None if current_user.is_superuser else current_user.tenant_id
    
    # 2. Verify project existence and user access
    project = crud.get_project(db, project_id=project_id, tenant_id=effective_tenant_id)
    if not project:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail="Project not found or not accessible."
        )
    
    # 3. Calculate and return the shortfall (shopping list)
    # The calculation logic resides in crud.py to keep the router clean
    shopping_list_items = crud.get_shopping_list_for_project(db, project_id=project_id)
    
    return shopping_list_items