"""Replace price_comparison_link with shop_urls in InventoryItem

Revision ID: 0f182bfac241
Revises: 45a7761ff54d
Create Date: 2025-05-02 22:53:37.891511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f182bfac241'
down_revision: Union[str, None] = '45a7761ff54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - START ###
    # These SHOULD be correct based on models.py vs current DB state (without price_comparison_link)
    op.add_column('inventory_items', sa.Column('shop_url_1', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('shop_url_2', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('shop_url_3', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # --- REMOVED Manually Added op.drop_column('inventory_items', 'price_comparison_link') ---
    # The column does not exist, so we don't try to drop it.


def downgrade() -> None:
    """Downgrade schema."""
    # --- REMOVED Manually Added op.add_column for price_comparison_link ---
    # We don't re-add it because it didn't exist before this migration's upgrade.

    # ### commands auto generated by Alembic - START ###
    # These SHOULD be correct based on models.py
    op.drop_column('inventory_items', 'shop_url_3')
    op.drop_column('inventory_items', 'shop_url_2')
    op.drop_column('inventory_items', 'shop_url_1')
    # ### end Alembic commands ###