"""Add quantity_needed to InventoryItem

Revision ID: <Your Revision ID, e.g., 179d9c5be049>
Revises: <Previous Revision ID>
Create Date: <Timestamp>

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179d9c5be049' # e.g., '179d9c5be049'
down_revision: Union[str, None] = 'cd1571ad2a6e' # e.g., '0f182bfac241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Added server_default='0.0' to handle existing rows
    op.add_column('inventory_items', sa.Column('quantity_needed', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'quantity_needed')
    # ### end Alembic commands ###