"""Change car oil change fields to integer for km

Revision ID: 204f53da201c
Revises: 376e455275ab
Create Date: 2025-10-10 20:08:20.400229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204f53da201c'
down_revision: Union[str, None] = '376e455275ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('last_oil_change_km', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('next_oil_change_due_km', sa.Integer(), nullable=True))
    op.drop_column('cars', 'next_oil_change_due_date')
    op.drop_column('cars', 'last_oil_change_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('last_oil_change_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('cars', sa.Column('next_oil_change_due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('cars', 'next_oil_change_due_km')
    op.drop_column('cars', 'last_oil_change_km')
    # ### end Alembic commands ###
