"""Add detailed car fleet models including tyres and logs

Revision ID: 376e455275ab
Revises: 84c2981fb4dc
Create Date: 2025-10-10 19:44:11.249828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376e455275ab'
down_revision: Union[str, None] = '84c2981fb4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('license_plate', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('Available', 'Checked_Out', 'In_Service', 'Needs_Service', 'Retired', name='carstatus'), nullable=False),
    sa.Column('last_oil_change_date', sa.Date(), nullable=True),
    sa.Column('next_oil_change_due_date', sa.Date(), nullable=True),
    sa.Column('service_needed', sa.Boolean(), nullable=False),
    sa.Column('service_notes', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('current_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_index(op.f('ix_cars_license_plate'), 'cars', ['license_plate'], unique=True)
    op.create_table('car_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.Enum('Checked_Out', 'Checked_In', 'Maintenance', 'Created', name='carlogaction'), nullable=False),
    sa.Column('odometer_reading', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_logs_id'), 'car_logs', ['id'], unique=False)
    op.create_table('tyre_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Summer', 'Winter', name='tyretype'), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_on_car', sa.Boolean(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tyre_sets_id'), 'tyre_sets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tyre_sets_id'), table_name='tyre_sets')
    op.drop_table('tyre_sets')
    op.drop_index(op.f('ix_car_logs_id'), table_name='car_logs')
    op.drop_table('car_logs')
    op.drop_index(op.f('ix_cars_license_plate'), table_name='cars')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
