"""Add details fields to Drawing model

Revision ID: 4112206ce2ef
Revises: 90135e016f72
Create Date: 2025-10-25 20:32:55.712841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4112206ce2ef'
down_revision: Union[str, None] = '90135e016f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawings', sa.Column('revision', sa.String(), nullable=True))
    op.add_column('drawings', sa.Column('discipline', sa.String(), nullable=True))
    op.add_column('drawings', sa.Column('status', sa.Enum('Draft', 'For_Approval', 'Approved', 'As_Built', 'Archived', name='drawingstatus'), nullable=True))
    op.add_column('drawings', sa.Column('drawing_date', sa.Date(), nullable=True))
    op.add_column('drawings', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawings', 'author')
    op.drop_column('drawings', 'drawing_date')
    op.drop_column('drawings', 'status')
    op.drop_column('drawings', 'discipline')
    op.drop_column('drawings', 'revision')
    # ### end Alembic commands ###
