"""Add labor catalog item table

Revision ID: 44f00c347751
Revises: 4112206ce2ef
Create Date: 2025-10-28 06:19:17.022817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f00c347751'
down_revision: Union[str, None] = '4112206ce2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labor_catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('default_unit_price', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labor_catalog_items_description'), 'labor_catalog_items', ['description'], unique=False)
    op.create_index(op.f('ix_labor_catalog_items_id'), 'labor_catalog_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labor_catalog_items_id'), table_name='labor_catalog_items')
    op.drop_index(op.f('ix_labor_catalog_items_description'), table_name='labor_catalog_items')
    op.drop_table('labor_catalog_items')
    # ### end Alembic commands ###
