"""Add can_export_data to User

Revision ID: 4a6d21dd0986
Revises: f9e2dc680578
Create Date: 2026-05-21 16:04:18.963726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6d21dd0986'
down_revision: Union[str, None] = 'f9e2dc680578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_export_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_export_data')
    # ### end Alembic commands ###
