"""Add project_manager_id to Project model and User relationship

Revision ID: 523ffa972b57
Revises: 50dbfac3029f
Create Date: 2025-05-14 21:06:35.984459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523ffa972b57'
down_revision: Union[str, None] = '50dbfac3029f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['project_manager_id'], ['id'])
    op.drop_constraint('time_logs_task_id_fkey', 'time_logs', type_='foreignkey')
    op.drop_constraint('time_logs_project_id_fkey', 'time_logs', type_='foreignkey')
    op.drop_constraint('time_logs_user_id_fkey', 'time_logs', type_='foreignkey')
    op.create_foreign_key(None, 'time_logs', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'time_logs', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'time_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_logs', type_='foreignkey')
    op.drop_constraint(None, 'time_logs', type_='foreignkey')
    op.drop_constraint(None, 'time_logs', type_='foreignkey')
    op.create_foreign_key('time_logs_user_id_fkey', 'time_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key('time_logs_project_id_fkey', 'time_logs', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('time_logs_task_id_fkey', 'time_logs', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'project_manager_id')
    # ### end Alembic commands ###
