"""Overhaul inventory for project-specific quantities

Revision ID: 5596173f5d3f
Revises: c914b90bcfb3
Create Date: 2025-10-17 22:19:56.793997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5596173f5d3f'
down_revision: Union[str, None] = 'c914b90bcfb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_inventory_items_id'), 'project_inventory_items', ['id'], unique=False)
    op.drop_column('inventory_items', 'quantity_needed')
    op.drop_column('inventory_items', 'location')
    op.drop_column('inventory_items', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('inventory_items', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('inventory_items', sa.Column('quantity_needed', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_project_inventory_items_id'), table_name='project_inventory_items')
    op.drop_table('project_inventory_items')
    # ### end Alembic commands ###
