"""add base_hourly_rate to tenant

Revision ID: 8b3cce251263
Revises: a1933c507381
Create Date: 2026-06-09 21:26:03.812569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3cce251263'
down_revision: Union[str, None] = 'a1933c507381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('base_hourly_rate', sa.Float(), nullable=False, server_default='6500.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'base_hourly_rate')
    # ### end Alembic commands ###
