"""Add local_image_path to InventoryItem model

Revision ID: a7affed04f8a
Revises: 7f78355b7546
Create Date: 2025-05-19 20:27:58.281945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7affed04f8a'
down_revision: Union[str, None] = '7f78355b7546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('local_image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'local_image_path')
    # ### end Alembic commands ###
