"""Make tenant_id on User nullable for superadmins

Revision ID: affbae9b957b
Revises: c6d9012e2798
Create Date: 2025-09-03 21:53:59.204428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'affbae9b957b'
down_revision: Union[str, None] = 'c6d9012e2798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
