"""Enhance tool model and add tool log history

Revision ID: c05b8bacfc2f
Revises: 9bd48557c141
Create Date: 2025-09-04 12:13:02.397949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05b8bacfc2f'
down_revision: Union[str, None] = '9bd48557c141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('tools', sa.Column('model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'model')
    op.drop_column('tools', 'brand')
    # ### end Alembic commands ###
