"""Add hourly_rate to User model

Revision ID: c6d9012e2798
Revises: 7c5f05a3baca
Create Date: 2025-08-08 20:42:46.700157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d9012e2798'
down_revision: Union[str, None] = '7c5f05a3baca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hourly_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hourly_rate')
    # ### end Alembic commands ###
