"""Add engineering fields to InventoryItem

Revision ID: f9e2dc680578
Revises: n2o3p4q5r6s7
Create Date: 2026-05-12 22:22:31.845578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e2dc680578'
down_revision: Union[str, None] = 'n2o3p4q5r6s7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('master_category', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('voltage', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('amperage', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('ip_rating', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('ar_labor_tasks_list', sa.Text(), nullable=True))
    op.create_index(op.f('ix_inventory_items_brand'), 'inventory_items', ['brand'], unique=False)
    op.create_index(op.f('ix_inventory_items_master_category'), 'inventory_items', ['master_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_master_category'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_brand'), table_name='inventory_items')
    op.drop_column('inventory_items', 'ar_labor_tasks_list')
    op.drop_column('inventory_items', 'ip_rating')
    op.drop_column('inventory_items', 'amperage')
    op.drop_column('inventory_items', 'voltage')
    op.drop_column('inventory_items', 'brand')
    op.drop_column('inventory_items', 'master_category')
    # ### end Alembic commands ###
